# Generated by Django 3.0.7 on 2020-06-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typePhone', models.CharField(choices=[('Internet', 'Internet'), ('Fixed', 'Fixed'), ('Fax', 'Fax'), ('Mci', 'Mci'), ('Irancell', 'Irancell'), ('Rightel', 'Rightel')], max_length=8)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeContact', models.CharField(choices=[('Real', 'Real'), ('Legal', 'Legal')], max_length=5)),
                ('fullName', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='contact/image')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.Phone')),
            ],
        ),
    ]
