# Generated by Django 3.0.7 on 2020-06-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='phonebook.Contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='typeContact',
            field=models.CharField(choices=[('Real', 'Real'), ('Legal', 'Legal')], default='Real', max_length=5),
        ),
        migrations.AlterField(
            model_name='phone',
            name='typePhone',
            field=models.CharField(choices=[('Internet', 'Internet'), ('Fixed', 'Fixed'), ('Fax', 'Fax'), ('Mci', 'Mci'), ('Irancell', 'Irancell'), ('Rightel', 'Rightel')], default='Mci', max_length=8),
        ),
    ]
